# INSTALL & UPGRADE OS PACKAGES

# INSTALL CONSUL + NOMAD + CERTIFICATES

- hosts: all
  become: yes
  roles:
    - ansible-role-consul
    - ansible-role-dnsmasq
    - ansible-role-nomad

- hosts: server
  become: yes
  roles:
    - ansible-role-server-certificates

- hosts: client
  become: yes
  roles:
    - ansible-role-client-certificates
    - ansible-role-docker
